services:
  - type: web
    name: tou-ai-assistant-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: touai
      - key: MONGODB_COLLECTION
        value: knowledge
